routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/*Route group access only  login user*/
Route::group(['middleware'=>'auth'],function() {
#redirect after successfully login
    Route::get('/home', function () {
        return view('welcome');
    })->name('home');

    /*Patient Route Start*/
    Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
        /*Patient add*/
        Route::get('add', ['uses' => 'PatientController@GetAddPatient'])->name('patientAdd');
        Route::post('add', ['uses' => 'PatientController@PostAddPatient']);
        Route::post('edit', ['uses' => 'PatientController@UpdatePatient'])->name('patientEdit');
        Route::post('delete', ['uses' => 'PatientController@DeletePatient'])->name('patientDelete');

        Route::get('list', ['uses' => 'PatientController@GetPatientList'])->name('getPatientList');
    });
    /*Patient Route end*/
    /*Schedule Route Start*/
    Route::group(['prefix' => 'schedule', 'as' => 'schedule.'], function () {
        /*Payment add to report*/
        Route::post('new/{reportId}', ['uses' => 'ScheduleController@addNewSchedule'])->name('addNew');

    });
    /*Schedule Route end*/

    /*Import-Export Route Start*/
    Route::group(['prefix' => 'import-export', 'as' => 'importExport.'], function () {
        /*Payment add to report*/
        Route::get('/', ['uses' => 'ExportImportController@getImportExportView'])->name('getView');
        Route::post('/import-file', ['uses' => 'ExportImportController@uploadExcelFile'])->name('uploadExcel');
        Route::get('/export-file/{type}', ['uses' => 'ExportImportController@downloadExcel'])->name('downloadExcel');


    });
    /*Imp-Export Route end*/

    /*Payment Route Start*/
    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        /*Payment add to report*/
        Route::get('report/{reportId}', ['uses' => 'PaymentController@GetReportPayment'])->name('report');

        Route::post('calculate/{reportId}', ['uses' => 'PaymentController@PostReportPayment'])->name('postPaymentAdd');
        Route::post('paid-clint', ['uses' => 'PaymentController@PaidClintFee'])->name('paid');

    });
    /*Payment Route end*/


    /*Report Route Start*/
    Route::group(['prefix' => 'report', 'as' => 'report.'], function () {
        /*Report add*/
        Route::get('patient-to-report/{patientId}', ['uses' => 'ReportController@GetReportView'])->name('toPatient');
        Route::get('add-report', ['uses' => 'ReportController@GetReportView'])->name('reportAdd');
        Route::post('post-report', ['uses' => 'ReportController@PostReportAdd'])->name('reportPost');
        Route::get('report-view/{reportId}', ['uses' => 'ReportController@GetReportDetails'])->name('reportDetails');
        Route::get('list', ['uses' => 'ReportController@GetReportList'])->name('list');
    });
    /*Report Route end*/

    /*Prescription Route Start*/
    Route::group(['prefix' => 'prescription', 'as' => 'prescription.'], function () {
        /*Prescription add view*/
        Route::get('report-to-prescription/{reportId}', ['uses' => 'PrescriptionController@GetPrescriptionView'])->name('prescriptionView');

        Route::get('prescription-list-report/{reportId}', ['uses' => 'PrescriptionController@GetPrescriptionListByReport'])->name('reportOldPrescription');

        /*Prescription add */
        Route::post('make-prescription/{reportId}','PrescriptionController@PostMakePrescription')->name('prescriptionMake');

        /*Prescription View*/
        Route::get('view/{prescriptionId}', ['uses' => 'PrescriptionController@GetPrescriptionDetails'])->name('prescriptionDetails');

        /*Prescription List*/
        Route::get('list-view', ['uses' => 'PrescriptionController@GetPrescriptionList'])->name('prescriptionList');

        /*Prescription Download*/
        Route::get('prescription-pdf/{prescriptionId}', ['uses' => 'PrescriptionController@DownloadPrescription'])->name('prescriptionDownload');

        /*Medicine List search */
        Route::post('medicine-search/','PrescriptionController@SearchMedicine')->name('liveMedicine');


    });
    /*Prescription Route end*/

    /*Setup Route Start*/
    Route::group(['prefix' => 'setup', 'as' => 'setup.'], function () {

        /*Get insert Data id*/
        Route::post('data-id', 'SetupController@GetSessionData')->name('dataId');

        /*Chief Complain Start*/
        Route::get('chief-complain', ['uses' => 'SetupController@GetChiefComplain'])->name('chiefComplain');
        Route::post('chief-complain', 'SetupController@PostChiefComplain')->name('postChiefComplain');
        Route::post('delete-chief-complain', 'SetupController@DeleteChiefComplain')->name('deleteComplian');
        Route::post('update-chief-complain', 'SetupController@UpdateChiefComplain')->name('updateComplian');

        /*Chief Complain End*/

        /*Examination Start*/
        Route::get('examination', 'SetupController@GetExamination')->name('getExamination');
        Route::post('examination-update', 'SetupController@CreateUpdateExamination')->name('CreateUpdateExamination');
        Route::post('examination-delete', 'SetupController@DeleteExamination')->name('deleteExamination');
        Route::post('examination-id', 'SetupController@GetSessionData')->name('examId');
        /*Examination End*/

        /*Medical history  Start*/
        Route::get('medical-history', 'SetupController@GetMedicalHistory')->name('history');
        Route::post('medical-history/insert', 'SetupController@AddMedicalHistory')->name('medicalHistoryAdd');
        Route::post('medical-history/update', 'SetupController@AddMedicalHistory')->name('MedicalHistoryEdit');
        Route::post('medical-history/delete', 'SetupController@DeleteMedicalHistory')->name('deleteMedicalHistory');

        /*Medical history End*/

        /*Advice Start*/
        Route::get('medical-advice', 'SetupController@GetAdvice')->name('advice');
        Route::post('medical-advice/insert', 'SetupController@AddUpdateAdvice')->name('AdviceAdd');
        Route::post('medical-advice/update', 'SetupController@AddUpdateAdvice')->name('AdviceDataEdit');
        Route::post('medical-advice/delete-data', 'SetupController@DeleteAdviceData')->name('deleteAdviceData');
        /*Advice End*/

        /*Treatment Cost Start*/
        Route::get('treatment-cost', 'SetupController@GetTreatmentCost')->name('treatmentCost');
        Route::post('treatment-cost/update', 'SetupController@AddEditTreatmentCost')->name('treatmentDataEdit');
        Route::post('treatment/delete', 'SetupController@DeleteTreatmentCost')->name('deletetreatmentData');
        Route::post('treatment/insert', 'SetupController@AddEditTreatmentCost')->name('treatmentAdd');
        /*Treatment Cost End*/

    });
    /*setup Route end*/




});

app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    protected $table = 'reports';
    protected $fillable = ['patient_id','report_create_date','report_create_time'];

    /*Report has a patient*/
    public function patient(){
        return $this->hasOne('App\Patient','id','patient_id');
    }

    #Report has many Chief Complain
    public function ReportChiefComplain(){
        return $this->hasMany('App\ReportComplains','report_id','id');
    }

    #Report has many Examination
    public function ReportExamination(){
        return $this->hasMany('App\ReportExamination','report_id','id');
    }
    #Report has many Location
    public function ReportSecondayLocation(){
        return $this->hasMany('App\ReportTeethLocation','report_id','id');
    }

    #Report has many Medical History
    public function ReportMedicalHistory(){
        return $this->hasMany('App\ReportMedicalHistory','report_id','id');
    }

    #Report has many advice
    public function ReportAdvice(){
        return $this->hasMany('App\ReportAdvice','report_id','id');
    }

    #Report has many Prescription
    public function ReportPrescription(){
        return $this->hasMany('App\Prescription','report_id','id');
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Advice;
use App\ChiefComplain;
use App\Examination;
use App\MedicalHistroy;
use App\Patient;
use App\Report;
use App\ReportAdvice;
use App\ReportComplains;
use App\ReportExamination;
use App\ReportMedicalHistory;
use App\ReportTeethLocation;
use Illuminate\Http\Request;

class ReportController extends Controller
{
    #get report view
    public function GetReportView($patientId){
        $patientDetail =Patient::where('id',$patientId)->first();

        if($patientDetail==null){
            return redirect()->route('patient.getPatientList');
        }

        $chiefComplain = ChiefComplain::all();
        $examination = Examination::all();
        $medicalHistory = MedicalHistroy::all();
        $adviceList = Advice::all();
        return view('report.addReport',[
            'chiefComplain'=>$chiefComplain,
            'examination'=>$examination,
            'medicalHistory'=>$medicalHistory,
            'adviceList'=>$adviceList,
            'patientDetail'=>$patientDetail
        ]);
    }

    #post req add report
    public function PostReportAdd(Request $request){
       //dd($request->all());
        $this->validate($request,[
            'patientId'=>'required|numeric',
            'chief_complain'=>'required|array',
            'locationOne'=>'required|array',
            'examination'=>'required|array',
            'locationTwo'=>'required|array',
            'medicalHistory'=>'required|array',
            'advice'=>'required|array',
        ],[
            'patientId.required'=>'Patient does not set',
            'patientId.numeric'=>'Patient data is invalid',
            'chief_complain.required'=>'Please select chief complain',
            'locationOne.required'=>'Primary location invalid',
            'examination.required'=>'Examination invalid',
            'locationTwo.required'=>'Secondary location invalid',
            'medicalHistory.required'=>'Medical history invalid',
            'advice.required'=>'Advice invalid',
        ]);

        $patientId = $request->input('patientId');
        $chiefComplainList = $request->input('chief_complain');
        $locationOneList = $request->input('locationOne');
        $examinationList = $request->input('examination');
        $locationTwoList = $request->input('locationTwo');
        $medicalHistoryList = $request->input('medicalHistory');
        $adviceList = $request->input('advice');
        $report = Report::create([
                    'patient_id'=>$patientId,
                    'report_create_date'=>date('Y-m-d'),
                    'report_create_time'=>date('h:i A'),
                ]);
        $insertedId = $report->id;
        foreach ($adviceList as $advice){
            ReportAdvice::create(['report_id'=>$insertedId,'advice_id'=>$advice]);
        }
        foreach ($chiefComplainList as $chiefComplain){
            ReportComplains::create(['report_id'=>$insertedId,'complain_id'=>$chiefComplain]);
        }
        foreach ($examinationList as $examination){
            ReportExamination::create(['report_id'=>$insertedId,'examination_id'=>$examination]);
        }
        foreach ($locationTwoList as $location){
            ReportTeethLocation::create(['report_id'=>$insertedId,'teeth_location_id'=>$location]);
        }
        foreach ($medicalHistoryList as $medicalHistory){
            ReportMedicalHistory::create(['report_id'=>$insertedId,'medical_history_id'=>$medicalHistory]);
        }

        return redirect()->route('report.reportDetails',['reportId'=>$insertedId]);
    }

    #Show report details by report id
    public function GetReportDetails($reportId){
        $reportDetails = Report::with(['patient','ReportChiefComplain','ReportExamination','ReportSecondayLocation','ReportMedicalHistory','ReportAdvice'])->where(['id'=>$reportId])->first();

        $chiefComplain = ChiefComplain::all();
        $examination = Examination::all();
        $medicalHistory = MedicalHistroy::all();
        $adviceList = Advice::all();
        return view('report.reportDetails',
            [
                'reportDetails'=>$reportDetails,'chiefComplain'=>$chiefComplain,
                'examination'=>$examination,
                'medicalHistory'=>$medicalHistory,
                'adviceList'=>$adviceList,
                'reportId'=>$reportId
            ]);
    }

    #get report list
    public function GetReportList(){
        $reportList = Report::with('patient')->get();
      //  dd($reportList);
        return view('report.reportList',['reportList'=>$reportList]);
    }
}

resources/views/report/reportList.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mr. Arif
 * Date: 12/2/2017
 * Time: 7:22 PM
 */
?>

@extends('layouts.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">


            <div class="header-icon">
                <i class="pe-7s-note2"></i>
            </div>
            <div class="header-title">
                <h1>Treatment</h1>
                <small> Treatment List Infromation</small>
                <ol class="breadcrumb hidden-xs">
                    <li><a href="javascript:void(0);"><i class="pe-7s-home"></i> Home</a></li>
                    <li class="active">Treatment info</li>
                </ol>
            </div>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="resultAjax"></div>
                    <div class="panel panel-bd lobidrag">
                        @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>
                            <script>
                                // notification
                                setTimeout(function () {
                                    toastr.options = {
                                        closeButton: true,
                                        progressBar: true,
                                        showMethod: 'slideDown',
                                        timeOut: 1000
                                    };
                                    toastr.success('Notification', 'Treatment Add Success');

                                }, 2300);
                            </script>

                        @endif
                        @if (count($errors) > 0)
                            <div class="alert">
                                @foreach ($errors->all() as $error)
                                    <p class="each-error">{{ $error }} </p>
                                @endforeach
                            </div>
                        @endif
                        <div class="panel-heading">

                            <div class="btn-group">
                                <!-- Trigger the modal with a button -->
                                <button data-toggle="modal" data-target="#myModal" class="btn btn-success">
                                    <i class="fa fa-plus"></i> Add Treatment
                                </button>
                                <!-- Modal -->
                                <div id="myModal" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->

                                        <div class="modal-content">
                                            <div class="modal-header bg-green bg-success">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title color-white">Add Treatment</h4>
                                            </div>
                                            <div class="modal-body">

                                                {{ Form::text('dataName', null,['class'=>"form-control",'placeholder'=>'Enter Treatment Name','id'=>"dataName"])}}
                                                <br/>
                                                {{ Form::text('dataCost', null,['class'=>"form-control",'placeholder'=>'Enter Treatment Cost','id'=>"dataCost"])}}

                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default closer" data-dismiss="modal">Close</button>

                                                <button onclick="addRowData()" type="button" class="btn btn-success">Save</button>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                {{--End modal--}}
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="panel-body">
                                <div id="example_wrapper" class="dataTables_wrapper">

                                    <table id="example" class="display nowrap dataTable dtr-inline" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
                                        <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 136px;">SL</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 136px;">Patient Name</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 136px;">Date</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 136px;">Time</th>
                                            <th class="dt-body-right sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 79px;">Action</th>
                                        </tr>
                                        </thead>
                                        <tfoot>

                                        <tr>
                                            <th rowspan="1" colspan="1">SL</th>
                                            <th rowspan="1" colspan="1">Patient Name</th>
                                            <th rowspan="1" colspan="1">Date</th>
                                            <th rowspan="1" colspan="1">Time</th>
                                            <th class="dt-body-right" rowspan="1" colspan="1">Action</th>
                                        </tr>
                                        </tfoot>
                                        <tbody id="tableBody">
                                        <?php
                                        $i =1;
                                        ?>
                                        @if($reportList->count()>0)
                                            @foreach($reportList as $report)
                                                <tr id="row{{$report->id}}" role="row" @if($i%2==0) class="odd" @else class="even" @endif>
                                                    <th class="count" rowspan="1" colspan="1">{{$i++}}</th>
                                                    <th class="insertDataName{{$report->id}}" rowspan="1" colspan="1">
                                                        {{$report->patient->name}}
                                                    </th>
                                                    <th class="insertDataCost{{$report->id}}" rowspan="1" colspan="1">
                                                        {{$report->report_create_date}}
                                                    </th>
                                                    <th class="insertDataCost{{$report->id}}" rowspan="1" colspan="1">
                                                        {{$report->report_create_time}}
                                                    </th>
                                                    <th class="" rowspan="1" colspan="1">


                                                        <span class="icon_box icon-elemet">
                                                            <a href="{{route('payment.report',['reportId'=>$report->id])}}">
                                                            <i class="hvr-buzz-out fa fa-dollar"></i>
                                                            </a>

                                                        </span>
                                                        <span  class="icon_box icon-elemet">
                                                            <a href="{{route('report.reportDetails',['reportId'=>$report->id])}}">
                                                            <i class="hvr-buzz-out fa fa-street-view"></i>
                                                            </a>
                                                        </span>
                                                    </th>
                                                </tr>
                                            @endforeach
                                        @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section> <!-- /.content -->
    </div> <!-- /.content-wrapper -->
    </div> <!-- /.content-wrapper -->

@endsection
@section('script')
    <script type="text/javascript">
        $(document).ready(function(){
            /*Add dataTabe of Patient list*/
            $('#example').DataTable();
            /*Active Menu from sidebar by add "active" Class*/
            $('span:contains("Report/Prescription")').parent().parent().addClass('active');
            $('a:contains("View Report")').parent().addClass('active');
        })
    </script>
@endsection