routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/*Route group access only  login user*/
Route::group(['middleware'=>'auth'],function() {
#redirect after successfully login
    Route::get('/home', function () {
        return view('welcome');
    })->name('home');

    /*Patient Route Start*/
    Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
        /*Patient add*/
        Route::get('add', ['uses' => 'PatientController@GetAddPatient'])->name('patientAdd');
        Route::post('add', ['uses' => 'PatientController@PostAddPatient']);
        Route::post('edit', ['uses' => 'PatientController@UpdatePatient'])->name('patientEdit');
        Route::post('delete', ['uses' => 'PatientController@DeletePatient'])->name('patientDelete');

        Route::get('list', ['uses' => 'PatientController@GetPatientList'])->name('getPatientList');
    });
    /*Patient Route end*/
    /*Schedule Route Start*/
    Route::group(['prefix' => 'schedule', 'as' => 'schedule.'], function () {
        /*Payment add to report*/
        Route::post('new/{reportId}', ['uses' => 'ScheduleController@addNewSchedule'])->name('addNew');

    });
    /*Schedule Route end*/

    /*Import-Export Route Start*/
    Route::group(['prefix' => 'import-export', 'as' => 'importExport.'], function () {
        /*Payment add to report*/
        Route::get('/', ['uses' => 'ExportImportController@getImportExportView'])->name('getView');
        Route::post('/import-file', ['uses' => 'ExportImportController@uploadExcelFile'])->name('uploadExcel');
        Route::get('/export-file/{type}', ['uses' => 'ExportImportController@downloadExcel'])->name('downloadExcel');


    });
    /*Imp-Export Route end*/

    /*Payment Route Start*/
    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        /*Payment add to report*/
        Route::get('report/{reportId}', ['uses' => 'PaymentController@GetReportPayment'])->name('report');

        Route::post('calculate/{reportId}', ['uses' => 'PaymentController@PostReportPayment'])->name('postPaymentAdd');
        Route::post('paid-clint', ['uses' => 'PaymentController@PaidClintFee'])->name('paid');

    });
    /*Payment Route end*/


    /*Report Route Start*/
    Route::group(['prefix' => 'report', 'as' => 'report.'], function () {
        /*Report add*/
        Route::get('patient-to-report/{patientId}', ['uses' => 'ReportController@GetReportView'])->name('toPatient');
        Route::get('add-report', ['uses' => 'ReportController@GetReportView'])->name('reportAdd');
        Route::post('post-report', ['uses' => 'ReportController@PostReportAdd'])->name('reportPost');
        Route::get('report-view/{reportId}', ['uses' => 'ReportController@GetReportDetails'])->name('reportDetails');
        Route::get('list', ['uses' => 'ReportController@GetReportList'])->name('list');
    });
    /*Report Route end*/

    /*Prescription Route Start*/
    Route::group(['prefix' => 'prescription', 'as' => 'prescription.'], function () {
        /*Prescription add view*/
        Route::get('report-to-prescription/{reportId}', ['uses' => 'PrescriptionController@GetPrescriptionView'])->name('prescriptionView');

        Route::get('prescription-list-report/{reportId}', ['uses' => 'PrescriptionController@GetPrescriptionListByReport'])->name('reportOldPrescription');

        /*Prescription add */
        Route::post('make-prescription/{reportId}','PrescriptionController@PostMakePrescription')->name('prescriptionMake');

        /*Prescription View*/
        Route::get('view/{prescriptionId}', ['uses' => 'PrescriptionController@GetPrescriptionDetails'])->name('prescriptionDetails');

        /*Prescription List*/
        Route::get('list-view', ['uses' => 'PrescriptionController@GetPrescriptionList'])->name('prescriptionList');

        /*Prescription Download*/
        Route::get('prescription-pdf/{prescriptionId}', ['uses' => 'PrescriptionController@DownloadPrescription'])->name('prescriptionDownload');

        /*Medicine List search */
        Route::post('medicine-search/','PrescriptionController@SearchMedicine')->name('liveMedicine');


    });
    /*Prescription Route end*/

    /*Setup Route Start*/
    Route::group(['prefix' => 'setup', 'as' => 'setup.'], function () {

        /*Get insert Data id*/
        Route::post('data-id', 'SetupController@GetSessionData')->name('dataId');

        /*Chief Complain Start*/
        Route::get('chief-complain', ['uses' => 'SetupController@GetChiefComplain'])->name('chiefComplain');
        Route::post('chief-complain', 'SetupController@PostChiefComplain')->name('postChiefComplain');
        Route::post('delete-chief-complain', 'SetupController@DeleteChiefComplain')->name('deleteComplian');
        Route::post('update-chief-complain', 'SetupController@UpdateChiefComplain')->name('updateComplian');

        /*Chief Complain End*/

        /*Examination Start*/
        Route::get('examination', 'SetupController@GetExamination')->name('getExamination');
        Route::post('examination-update', 'SetupController@CreateUpdateExamination')->name('CreateUpdateExamination');
        Route::post('examination-delete', 'SetupController@DeleteExamination')->name('deleteExamination');
        Route::post('examination-id', 'SetupController@GetSessionData')->name('examId');
        /*Examination End*/

        /*Medical history  Start*/
        Route::get('medical-history', 'SetupController@GetMedicalHistory')->name('history');
        Route::post('medical-history/insert', 'SetupController@AddMedicalHistory')->name('medicalHistoryAdd');
        Route::post('medical-history/update', 'SetupController@AddMedicalHistory')->name('MedicalHistoryEdit');
        Route::post('medical-history/delete', 'SetupController@DeleteMedicalHistory')->name('deleteMedicalHistory');

        /*Medical history End*/

        /*Advice Start*/
        Route::get('medical-advice', 'SetupController@GetAdvice')->name('advice');
        Route::post('medical-advice/insert', 'SetupController@AddUpdateAdvice')->name('AdviceAdd');
        Route::post('medical-advice/update', 'SetupController@AddUpdateAdvice')->name('AdviceDataEdit');
        Route::post('medical-advice/delete-data', 'SetupController@DeleteAdviceData')->name('deleteAdviceData');
        /*Advice End*/

        /*Treatment Cost Start*/
        Route::get('treatment-cost', 'SetupController@GetTreatmentCost')->name('treatmentCost');
        Route::post('treatment-cost/update', 'SetupController@AddEditTreatmentCost')->name('treatmentDataEdit');
        Route::post('treatment/delete', 'SetupController@DeleteTreatmentCost')->name('deletetreatmentData');
        Route::post('treatment/insert', 'SetupController@AddEditTreatmentCost')->name('treatmentAdd');
        /*Treatment Cost End*/

    });
    /*setup Route end*/




});

app/Prescription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prescription extends Model
{
    protected $table = 'prescriptions';

    protected $fillable = ['report_id','date','time','c_c','o_e','advice'];


    #Prescription has many Medicine
    public function PrescriptionMedicine(){
        return $this->hasMany('App\Medicine','prescription_id','id');
    }

    #Prescription has many Medicine
    public function PrescriptionReport(){
        return $this->belongsTo('App\Report','report_id');
    }
}

app/Http/Controllers/PrescriptionController.php
<?php

namespace App\Http\Controllers;

use App\ExportImport;
use App\Medicine;
use App\Prescription;
use App\Report;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use PDF;

class PrescriptionController extends Controller
{
    #Make prescription get view
    public function GetPrescriptionView($reportId){
        $reportDetails = Report::with('patient')->where(['id'=>$reportId])->first();
        return view('prescription.prescriptionView',['reportDetails'=>$reportDetails]);
    }

    #prescription make by post request
    public function PostMakePrescription($reportId,Request $request){

        $this->validate($request,[
            'c/c'=>'required',
            'o/e'=>'required',
            'advice'=>'required',
            'medicine_name'=>'required|array',
            'meal'=>'required|array',
            'morning'=>'required|array',
            'evening'=>'required|array',
            'night'=>'required|array',
        ],[
            'c/c.required'=>'C/C is required',
            'o/e.required'=>'Q/E is required',
            'advice.required'=>'Advice is required',
            'medicine_name.required'=>'Medicine name does not found',
            'medicine_name.array'=>'Medicine name is invalid',
            'meal.required'=>'Meal time is required',
            'meal.array'=>'Meal time is invalid',
            'morning.required'=>'Morning time is required',
            'morning.array'=>'Morning time is invalid',
            'evening.required'=>'Evening time is required',
            'evening.array'=>'Evening time is invalid',
            'night.required'=>'Night time is required',
            'night.array'=>'Night time is invalid',
        ]);

        $c_c = $request->input('c/c');
        $o_e = $request->input('o/e');
        $advice = $request->input('advice');
        $medicineName = $request->input('medicine_name');
        $meal = $request->input('meal');
        $morning = $request->input('morning');
        $evening = $request->input('evening');
        $night = $request->input('night');

        $prescription=    Prescription::create([
                                'report_id'=>$reportId,
                                'date'=>date('d-m-Y'),
                                'time'=>date('h:i A'),
                                'c_c'=>$c_c,
                                'o_e'=>$o_e,
                                'advice'=>$advice
                            ]);
        $prescriptionId = $prescription->id;
        for ($i =0; $i<sizeof($medicineName);$i++){
            Medicine::create([
                'prescription_id'=>$prescriptionId,
                'medicine_name'=>$medicineName[$i],
                'meal_time'=>$meal[$i],
                'morning'=>$morning[$i],
                'evening'=>$evening[$i],
                'night'=>$night[$i],
            ]);
        }
        return redirect()->route('prescription.prescriptionDetails',['prescriptionId'=>$prescriptionId])->with('status','Presctiption Make Succefully Done!!!');
    }

    #Get Prescription detalils
    public function GetPrescriptionDetails($precriptionId){
        $prescriptionDetails = Prescription::with('PrescriptionMedicine')->where(['id'=>$precriptionId])->first();
        $reportDetails = Report::with('patient')->where(['id'=>$prescriptionDetails->report_id])->first();

        return view('prescription.prescriptionDetails',['prescriptionDetails'=>$prescriptionDetails,'reportDetails'=>$reportDetails]);
    }

    #Get Prescription list by report id
    public function GetPrescriptionListByReport($reportId){

        $prescriptionList= DB::table('prescriptions')
            ->select('prescriptions.id','prescriptions.date','prescriptions.time','patients.name','patients.mobile')
            ->join('reports', 'prescriptions.report_id', '=', 'reports.id')
            ->join('patients', 'reports.patient_id', '=', 'patients.id')
            ->where('reports.id',$reportId)
            ->get();
        if($prescriptionList->count()==0){
            Session::flash('message', 'Make the first prescription....');
            return redirect()->back()->with('message', 'Make the first prescription....');
        }
        return view('prescription.prescriptionList',['prescriptionList'=>$prescriptionList]);
    }

    #Get All prescription list
    public function GetPrescriptionList(){
        $prescriptionList= DB::table('prescriptions')
                            ->select('prescriptions.id','prescriptions.date','prescriptions.time','patients.name','patients.mobile')
                            ->join('reports', 'prescriptions.report_id', '=', 'reports.id')
                            ->join('patients', 'reports.patient_id', '=', 'patients.id')

                            ->get();

        return view('prescription.prescriptionList',['prescriptionList'=>$prescriptionList]);
    }

    /*Download prescription pdf*/
    public function DownloadPrescription($precriptionId){
        $prescriptionDetails = Prescription::with('PrescriptionMedicine')->where(['id'=>$precriptionId])->first();
        $reportDetails = Report::with('patient')->where(['id'=>$prescriptionDetails->report_id])->first();

        //return view('pdf.prescription',['prescriptionDetails'=>$prescriptionDetails,'reportDetails'=>$reportDetails]);

        $pdf = PDF::loadView('pdf.prescription',['prescriptionDetails'=>$prescriptionDetails,'reportDetails'=>$reportDetails]);
        return $pdf->stream('document.pdf');
    }

    #Search medicine for live search by ajax request
    public function SearchMedicine(Request $request){
        $key = $request->input('value');
        $medicineList = ExportImport::limit(4)->where('medicine_name', 'LIKE', '%'.$key.'%')->get()->unique();
        if($medicineList->count()>0){
            echo "<ul class='search-result'>";
            foreach ($medicineList as $medicine){
                echo    '<li class="result-list"><span class="medicineName">'.$medicine->medicine_name.'</span></li>';
               /* echo '<li>'.
                        '<td>'.$medicine->medicine_name.'</td>'.

                        '<td>'.$medicine->contains.'</td>'.

                        '<td>'.$medicine->dosage_form.'</td>'.

                        '<td>'.$medicine->manufacturer.'</td>'.
                    '</li>';*/
            }
            echo "</ul>";
        }


    }
}

resources/views/prescription/prescriptionView.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mr. Lab
 * Date: 12/1/2017
 * Time: 8:33 PM
 */ ?>

@extends('layouts.master')
@section('content')
<script language="javascript">

    var tablSl = 1;
    var count=1;
    //add a new row to the table
    function addRow() {
        tablSl=+tablSl + +count;
        //add a row to the rows collection and get a reference to the newly added row
        var newRow = document.all("tblGrid").insertRow();

        //add 3 cells (<td>) to the new row and set the innerHTML to contain text boxes
        var oCell = newRow.insertCell();
        oCell.innerHTML = tablSl;

        var oCell = newRow.insertCell();
        oCell.innerHTML = "<input class='form-control medicine_data' type='text' name='medicine_name[]'>";

        var oCell = newRow.insertCell();
        oCell.innerHTML = '<select name="meal[]">\n' +
            '<option value="1">After</option>\n' +
            '<option value="0">Before</option>\n' +
            '</select>';

        oCell = newRow.insertCell();
        oCell.innerHTML = "<input class='form-control' type='text' name='morning[]'>";

        oCell = newRow.insertCell();
        oCell.innerHTML = "<input  class='form-control' type='text' name='evening[]'> ";

        oCell = newRow.insertCell();
        oCell.innerHTML = "<input  class='form-control' type='text' name='night[]'> ";

        oCell = newRow.insertCell();
        oCell.innerHTML = "<input type='button' value='X' onclick='removeRow(this);'/> ";


    }

    //deletes the specified row from the table
    function removeRow(src) {
        /* src refers to the input button that was clicked.
         to get a reference to the containing <tr> element,
         get the parent of the parent (in this case case <tr>)
         */
        var oRow = src.parentElement.parentElement;

        //once the row reference is obtained, delete it passing in its rowIndex
        document.all("tblGrid").deleteRow(oRow.rowIndex);
    }

</script>
<!-- =============================================== -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <div class="header-icon">
            <i class="pe-7s-note2"></i>
        </div>
        <div class="header-title">
            <h1> Add Prescription </h1>
            <small> Prescription Infromation</small>
            <ol class="breadcrumb hidden-xs">
                <li><a href="{{route('home')}}"><i class="pe-7s-home"></i> Home</a></li>
                <li class="active">Add Prescription</li>
            </ol>
        </div>
    </section>
    <!-- Main content -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- Form controls -->
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="PrescriptionView.php"> <i class="fa fa-list"></i> Prescription View </a>
                        </div>
                    </div>

                    <div class="panel-body">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    {{ $error }}<br>
                                @endforeach
                            </div>
                        @endif
                        <form action="{{route('prescription.prescriptionMake',['reportId'=>$reportDetails->id])}}" class="col-sm-12" method="POST">
                            <div class="row">

                                {{csrf_field()}}
                                <div class="col-sm-6 form-group">
                                    <label>Patient Name: </label>
                                    {{$reportDetails->patient->name}}
                                </div>
                                <div class="col-sm-6 form-group">
                                    <label>Age: </label>
                                    {{$reportDetails->patient->age}}
                                </div>
                                <div class="col-sm-6 form-group">
                                    <label>Gender: </label>
                                    {{$reportDetails->patient->sex}}
                                </div>
                                <div class="col-sm-6 form-group">
                                    <label>Date: </label>
                                    {{date('d-m-Y')}}
                                </div>
                                <div class="col-sm-12 form-group">
                                    <label>C/C</label>
                                    <textarea name="c/c" id="some-textarea" class="form-control" rows="3" placeholder="Enter C/C ..."></textarea>
                                </div>
                                <div class="col-sm-12 form-group">
                                    <label>O/E</label>
                                    <textarea name="o/e" id="some-textarea" class="form-control" rows="3" placeholder="Enter O/E ..."></textarea>
                                </div>

                                <div class="col-sm-12 form-group">
                                    <label>Adv</label>
                                    <textarea name="advice" id="some-textarea" class="form-control" rows="3" placeholder="Enter Advice ..."></textarea>
                                </div>

                            </div>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover" cellspacing="0" width="100%" id="tblGrid">
                                <thead>
                                <tr>
                                    <th> No</th>
                                    <th>Medicine Name</th>
                                    <th> Before Meal</th>
                                    <th>Morning</th>
                                    <th>Evening</th>
                                    <th>Night</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody id="tbl_body">
                                <tr>
                                    <td class="sl_no" width="10px">1</td>
                                    <td width="200px">
                                        <input class="form-control medicine_data" type="text" name="medicine_name[]" />
                                    </td>
                                    <td width="5px">
                                        <select name="meal[]">
                                            <option value="1">After</option>
                                            <option value="0">Before</option>
                                        </select>
                                        {{--<input class="form-control" type="checkbox" name="meal[]" />--}}
                                    </td>
                                    <td width="200px">
                                        <input class="form-control" type="text" name="morning[]" />
                                    </td>
                                    <td width="200px">
                                        <input class="form-control" type="text" name="evening[]" />
                                    </td>
                                    <td width="200px">
                                        <input class="form-control" type="text" name="night[]" /> </td>
                                    <td width="10px">
                                        <input type="button" value="X" onclick="removeRow(this);" />
                                    </td>
                                </tr>

                                </tbody>
                            </table>

                            <hr>
                            <input type="button" value="Add Row" onclick="addRow();" />
                            <div class="col-sm-12 reset-button">
                                <a href="#" class="btn btn-warning">Reset</a>
                                <input class="btn btn-success" type="submit" value="Save">

                            </div>
                        </div>


                    </form>
                    </div>

                </div>
            </div>
        </div>


    </section>
    <!-- /.content -->

</div>
<!-- /.content-wrapper -->
@endsection

@section('script')
    <script type="text/javascript">
        /*Script start for live search*/
        $(document).ready(function(){
            $(document).on('keyup', '.medicine_data', function(){
                var thisElement = $(this);
                var value = thisElement.val();
                if(value.length>=2) {
                    /*Send ajax request to get list data*/
                    $.ajax({
                        url: '{{route('prescription.liveMedicine')}}',
                        type: 'POST',
                        data: {'_token': '{{csrf_token()}}', 'value': value},
                        success: function (result) {
                            $('.search-result').hide();
                            thisElement.parent().append(result);
                        }
                    });
                }else{
                    $('.search-result').hide();
                }
            });
        });
        /*Script end for live-search*/

        /*Set a value to input field for live search*/
        $(document).on('click', '.result-list', function(){

           $(this).parent().parent().find('.medicine_data').val($(this).find('.medicineName').text());
            $(this).parent().hide();
        });

        /*Remove search-result when click out-side*/
        $(document).mouseup(function(e)
        {
            var container = $('.search-result');
            // if the target of the click isn't the container nor a descendant of the container
            if (!container.is(e.target) && container.has(e.target).length === 0)
            {
                container.hide();
            }
        });
    </script>


@endsection