routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/*Route group access only  login user*/
Route::group(['middleware'=>'auth'],function() {
#redirect after successfully login
    Route::get('/home', function () {
        return view('welcome');
    })->name('home');

    /*Patient Route Start*/
    Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
        /*Patient add*/
        Route::get('add', ['uses' => 'PatientController@GetAddPatient'])->name('patientAdd');
        Route::post('add', ['uses' => 'PatientController@PostAddPatient']);
        Route::post('edit', ['uses' => 'PatientController@UpdatePatient'])->name('patientEdit');
        Route::post('delete', ['uses' => 'PatientController@DeletePatient'])->name('patientDelete');

        Route::get('list', ['uses' => 'PatientController@GetPatientList'])->name('getPatientList');
    });
    /*Patient Route end*/
    /*Schedule Route Start*/
    Route::group(['prefix' => 'schedule', 'as' => 'schedule.'], function () {
        /*Payment add to report*/
        Route::post('new/{reportId}', ['uses' => 'ScheduleController@addNewSchedule'])->name('addNew');

    });
    /*Schedule Route end*/

    /*Import-Export Route Start*/
    Route::group(['prefix' => 'import-export', 'as' => 'importExport.'], function () {
        /*Payment add to report*/
        Route::get('/', ['uses' => 'ExportImportController@getImportExportView'])->name('getView');
        Route::post('/import-file', ['uses' => 'ExportImportController@uploadExcelFile'])->name('uploadExcel');
        Route::get('/export-file/{type}', ['uses' => 'ExportImportController@downloadExcel'])->name('downloadExcel');


    });
    /*Imp-Export Route end*/

    /*Payment Route Start*/
    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        /*Payment add to report*/
        Route::get('report/{reportId}', ['uses' => 'PaymentController@GetReportPayment'])->name('report');

        Route::post('calculate/{reportId}', ['uses' => 'PaymentController@PostReportPayment'])->name('postPaymentAdd');
        Route::post('paid-clint', ['uses' => 'PaymentController@PaidClintFee'])->name('paid');

    });
    /*Payment Route end*/


    /*Report Route Start*/
    Route::group(['prefix' => 'report', 'as' => 'report.'], function () {
        /*Report add*/
        Route::get('patient-to-report/{patientId}', ['uses' => 'ReportController@GetReportView'])->name('toPatient');
        Route::get('add-report', ['uses' => 'ReportController@GetReportView'])->name('reportAdd');
        Route::post('post-report', ['uses' => 'ReportController@PostReportAdd'])->name('reportPost');
        Route::get('report-view/{reportId}', ['uses' => 'ReportController@GetReportDetails'])->name('reportDetails');
        Route::get('list', ['uses' => 'ReportController@GetReportList'])->name('list');
    });
    /*Report Route end*/

    /*Prescription Route Start*/
    Route::group(['prefix' => 'prescription', 'as' => 'prescription.'], function () {
        /*Prescription add view*/
        Route::get('report-to-prescription/{reportId}', ['uses' => 'PrescriptionController@GetPrescriptionView'])->name('prescriptionView');

        Route::get('prescription-list-report/{reportId}', ['uses' => 'PrescriptionController@GetPrescriptionListByReport'])->name('reportOldPrescription');

        /*Prescription add */
        Route::post('make-prescription/{reportId}','PrescriptionController@PostMakePrescription')->name('prescriptionMake');

        /*Prescription View*/
        Route::get('view/{prescriptionId}', ['uses' => 'PrescriptionController@GetPrescriptionDetails'])->name('prescriptionDetails');

        /*Prescription List*/
        Route::get('list-view', ['uses' => 'PrescriptionController@GetPrescriptionList'])->name('prescriptionList');

        /*Prescription Download*/
        Route::get('prescription-pdf/{prescriptionId}', ['uses' => 'PrescriptionController@DownloadPrescription'])->name('prescriptionDownload');

        /*Medicine List search */
        Route::post('medicine-search/','PrescriptionController@SearchMedicine')->name('liveMedicine');


    });
    /*Prescription Route end*/

    /*Setup Route Start*/
    Route::group(['prefix' => 'setup', 'as' => 'setup.'], function () {

        /*Get insert Data id*/
        Route::post('data-id', 'SetupController@GetSessionData')->name('dataId');

        /*Chief Complain Start*/
        Route::get('chief-complain', ['uses' => 'SetupController@GetChiefComplain'])->name('chiefComplain');
        Route::post('chief-complain', 'SetupController@PostChiefComplain')->name('postChiefComplain');
        Route::post('delete-chief-complain', 'SetupController@DeleteChiefComplain')->name('deleteComplian');
        Route::post('update-chief-complain', 'SetupController@UpdateChiefComplain')->name('updateComplian');

        /*Chief Complain End*/

        /*Examination Start*/
        Route::get('examination', 'SetupController@GetExamination')->name('getExamination');
        Route::post('examination-update', 'SetupController@CreateUpdateExamination')->name('CreateUpdateExamination');
        Route::post('examination-delete', 'SetupController@DeleteExamination')->name('deleteExamination');
        Route::post('examination-id', 'SetupController@GetSessionData')->name('examId');
        /*Examination End*/

        /*Medical history  Start*/
        Route::get('medical-history', 'SetupController@GetMedicalHistory')->name('history');
        Route::post('medical-history/insert', 'SetupController@AddMedicalHistory')->name('medicalHistoryAdd');
        Route::post('medical-history/update', 'SetupController@AddMedicalHistory')->name('MedicalHistoryEdit');
        Route::post('medical-history/delete', 'SetupController@DeleteMedicalHistory')->name('deleteMedicalHistory');

        /*Medical history End*/

        /*Advice Start*/
        Route::get('medical-advice', 'SetupController@GetAdvice')->name('advice');
        Route::post('medical-advice/insert', 'SetupController@AddUpdateAdvice')->name('AdviceAdd');
        Route::post('medical-advice/update', 'SetupController@AddUpdateAdvice')->name('AdviceDataEdit');
        Route::post('medical-advice/delete-data', 'SetupController@DeleteAdviceData')->name('deleteAdviceData');
        /*Advice End*/

        /*Treatment Cost Start*/
        Route::get('treatment-cost', 'SetupController@GetTreatmentCost')->name('treatmentCost');
        Route::post('treatment-cost/update', 'SetupController@AddEditTreatmentCost')->name('treatmentDataEdit');
        Route::post('treatment/delete', 'SetupController@DeleteTreatmentCost')->name('deletetreatmentData');
        Route::post('treatment/insert', 'SetupController@AddEditTreatmentCost')->name('treatmentAdd');
        /*Treatment Cost End*/

    });
    /*setup Route end*/




});

resources/views/include/afterScript.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Md. Arif
 * Date: 10/31/2017
 * Time: 12:15 AM
 */
?>


</body>
</html>

resources/views/include/footer.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Arif
 * Date: 10/30/2017
 * Time: 3:24 PM
 */
?>
<footer class="main-footer">
    <div class="pull-right hidden-xs"> <b>Version</b> 1.0</div>
    <strong>Copyright &copy; 2016-2017 <a href="#">DifferentCoder</a>.</strong> All rights reserved.
</footer>
</div> <!-- ./wrapper -->
<!-- ./wrapper -->
<!-- Start Core Plugins
=====================================================================-->
<!-- jQuery -->
<script src="{{ asset('assets/plugins/jQuery/jquery-1.12.4.min.js')}}" type="text/javascript"></script>
<!-- jquery-ui -->
<script src="{{ asset('assets/plugins/jquery-ui-1.12.1/jquery-ui.min.js')}}" type="text/javascript"></script>
<!-- Bootstrap -->
<script src="{{ asset('assets/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<!-- lobipanel -->
<script src="{{ asset('assets/plugins/lobipanel/lobipanel.min.js')}}" type="text/javascript"></script>

{{--modal--}}
<script src="{{ asset('assets/plugins/modals/modalEffects.js')}}" type="text/javascript"></script>
<!-- Pace js -->
<script src="{{ asset('assets/plugins/pace/pace.min.js')}}" type="text/javascript"></script>
<!-- SlimScroll -->
<script src="{{ asset('assets/plugins/slimScroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
<!-- FastClick -->
<script src="{{ asset('assets/plugins/fastclick/fastclick.min.js')}}" type="text/javascript"></script>

<!-- Hadmin frame -->
<script src="{{ asset('assets/dist/js/custom1.js')}}" type="text/javascript"></script>
<!-- End Core Plugins
=====================================================================-->
<!-- Start Page Lavel Plugins
=====================================================================-->
<!-- Toastr js -->
<script src="{{ asset('assets/plugins/toastr/toastr.min.js')}}" type="text/javascript"></script>
<!-- Sparkline js -->
<script src="{{ asset('assets/plugins/sparkline/sparkline.min.js')}}" type="text/javascript"></script>
<!-- Data maps js -->
<script src="{{ asset('assets/plugins/datamaps/d3.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/datamaps/topojson.min.js')}}" type="text/javascript"></script>

<!-- Counter js -->
<script src="{{ asset('assets/plugins/counterup/waypoints.js')}}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/counterup/jquery.counterup.min.js')}}" type="text/javascript"></script>
<!-- ChartJs JavaScript -->
<script src="{{ asset('assets/plugins/chartJs/Chart.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/emojionearea/emojionearea.min.js')}}" type="text/javascript"></script>
<!-- Monthly js -->
<script src="{{ asset('assets/plugins/monthly/monthly.js')}}" type="text/javascript"></script>
<!-- Data maps -->
<script src="{{ asset('assets/plugins/datamaps/d3.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/datamaps/topojson.min.js')}}" type="text/javascript"></script>




<!-- End Page Lavel Plugins
=====================================================================-->
<!-- Start Theme label Script
=====================================================================-->
<!-- Dashboard js -->
<script src="{{ asset('assets/dist/js/custom.js')}}" type="text/javascript"></script>

<!-- End Theme label Script
=====================================================================-->
<script>
    function nextDate(myDate,separator,incrementDate){
        var sDate =myDate.split(separator)[0];
        var sMonth =myDate.split(separator)[1];
        var sYear=myDate.split(separator)[2];
        var sFullDate = sMonth+separator+sDate+separator+sYear;
        var date = new Date(sFullDate);
        date.setDate(date.getDate()+1);
        var dd = date.getDate();
        var mm = date.getMonth() + 1;
        var y = date.getFullYear();
        alert(dd);
    }
    /*Script start for datepicker*/
    $(document).ready(function(){
        var lastDate = 1;
        $(document).on('click', '.datepicker', function(){
            $(this).datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "dd-mm-yy",
                minDate: lastDate,
                maxDate: '+3M',
                onSelect: function(dateText) {
                    lastDate = dateText;
               /*     nextDate(dateText,"-","1");*/
                }
            }).focus();
            $(this).removeClass('datepicker');
        });
    });
    /*Script end for datepicker*/

    function clearInputField(){
        $("#dataName").val('');
        $("#dataCost").val('');
    }
    /*Show notification*/
    function Notification(Message) {
        setTimeout(function () {
            toastr.options = {
                closeButton: true,
                progressBar: true,
                showMethod: 'slideDown',
                timeOut: 2000
            };
            toastr.success('Notification', Message);
        }, 200);
    }


</script>

<script src="{{ asset('assets/data-table/dataTables.min.js')}}" type="text/javascript"></script>

resources/views/include/header.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Arif
 * Date: 10/30/2017
 * Time: 3:23 PM
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin panel</title>
    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{{ asset('assets/dist/img/ico/favicon.png') }}" type="image/x-icon">
    <!-- Start Global Mandatory Style !-->
    <!-- =====================================================================-->

    <link href="{{ asset('assets/plugins/jquery-ui-1.12.1/jquery-ui-1.11.2.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Bootstrap -->
    <link href="{{ asset('assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Bootstrap rtl -->
<!--<link href="{{ asset('assets/bootstrap-rtl/bootstrap-rtl.min.css') }}" rel="stylesheet" type="text/css"/>-->
    <!-- Lobipanel css -->
    <link href="{{ asset('assets/plugins/lobipanel/lobipanel.min.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Pace css -->
    <link href="{{ asset('assets/plugins/pace/flash.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Font Awesome -->
    <link href="{{ asset('assets/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Pe-icon -->
    <link href="{{ asset('assets/pe-icon-7-stroke/css/pe-icon-7-stroke.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Themify icons -->
    <link href="{{ asset('assets/themify-icons/themify-icons.css') }}" rel="stylesheet" type="text/css"/>
    {{--Data table css--}}
    <link rel="stylesheet" href="{{ asset('assets/data-table/dataTables.min.css')}}" />

    <!-- End Global Mandatory Style
    =====================================================================-->
    <!-- Start page Label Plugins
    =====================================================================-->
    <!-- Toastr css -->
    <link href="{{ asset('assets/plugins/toastr/toastr.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Emojionearea -->
    <link href="{{ asset('assets/plugins/emojionearea/emojionearea.min.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Monthly css -->
    <link href="{{ asset('assets/plugins/monthly/monthly.css') }}" rel="stylesheet" type="text/css"/>
    <!-- End page Label Plugins
    =====================================================================-->
    <!-- Start Theme Layout Style
    =====================================================================-->
    <!-- Theme style -->
    <link href="{{ asset('assets/dist/css/stylehealth.min.css') }}" rel="stylesheet" type="text/css"/>

    {{--Dropzone CSS--}}
    <link href="{{ asset('assets/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('assets/dropzone/basic.min.css') }}" rel="stylesheet" type="text/css"/>

    <link href="{{ asset('assets/style.css') }}" rel="stylesheet" type="text/css"/>
    <!-- End Theme Layout Style
    =====================================================================-->
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
    <header class="main-header">
        <a href="{{route('home')}}" class="logo"> <!-- Logo -->
            <span class="logo-mini">
                        <!--<b>A</b>H-admin-->
                        <img src="{{ asset('assets/dist/img/mini-logo.png')}}" alt="">
                    </span>
            <span class="logo-lg">
                        <!--<b>Admin</b>H-admin-->
                        <img src="{{ asset('assets/dist/img/logo.png')}}" alt="">
                    </span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top ">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"> <!-- Sidebar toggle button-->
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-tasks"></span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    <li class="dropdown dropdown-user admin-user">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <div class="user-image">
                                <img src="{{ asset('assets/dist/img/avatar4.png')}}" class="img-circle" height="40" width="40" alt="User Image">
                            </div>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="profile.html"><i class="fa fa-users"></i> User Profile</a></li>
                            <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

resources/views/include/sidebar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Arif
 * Date: 10/30/2017
 * Time: 3:25 PM
 */
?>
<!-- =============================================== -->
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="image pull-left">
                <img src="{{ asset('assets/dist/img/avatar5.png')}}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <h4>Welcome</h4>
                <p>Mr. Alrazy</p>
            </div>
        </div>

        <!-- sidebar menu -->
        <ul class="sidebar-menu">
            <li>
                <a href="{{route('home')}}"><i class="fa fa-hospital-o"></i><span>Dashboard</span>
                </a>
            </li>

            <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-user"></i><span>Patient</span>
                    <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('patient.patientAdd')}}">Add patient</a></li>
                    <li><a href="{{route('patient.getPatientList')}}">Patient list</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-sitemap"></i><span>Report/Prescription</span>
                    <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('report.list')}}">View Report</a></li>
                    <li><a href="{{route('prescription.prescriptionList')}}">View Prescription</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-list-alt"></i> <span>Payment</span>
                    <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="TreatmentCost.php">Treatment Cost</a></li>
                    <li><a href="PaymentSchedule.php">Payment Schedule</a></li>

                </ul>
            </li>
            <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="glyphicon glyphicon-wrench"></i> <span>Setup</span>
                    <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('setup.chiefComplain')}}">Chief Complain</a></li>
                    <li><a href="{{route('setup.getExamination')}}">Examination</a></li>
                    <li><a href="{{route('setup.history')}}">Medical History/Problem</a></li>
                    <li><a href="{{route('setup.advice')}}">Advice</a></li>
                    <li><a href="{{route('setup.treatmentCost')}}">Treatment Cost</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="{{route('importExport.getView')}}">
                    <i class="fa fa-list-alt"></i> <span>Export / Import</span>

                </a>

            </li>
        </ul>
    </div> <!-- /.sidebar -->
</aside>